### ISSUE TITLE
Slash commandes accessibles à everyone lorsqu'on invite le bot sur un serveur

### ISSUE THREAD

**Issue by Enaxom** [EpsiTeam/epsibot#126]
![image](https://user-images.githubusercontent.com/40228349/220209209-aa3325c1-af03-4b18-84a7-5309e82a115b.png)

**Comment by Wyzedix** [comment]
Heu je reproduit pas, l'interface est pas clair mais les commandes ne sont pas accessibles à tout le monde

Serveur Epsilon (Epsibot 2.8.1) -> Settings -> Integration -> /autorole
![image](https://user-images.githubusercontent.com/46866540/221368578-f3c764e9-dda1-481d-af6a-9896fbe99f01.png)

View required permissions
![image](https://user-images.githubusercontent.com/46866540/221368587-776a214d-01ec-4d6f-889c-4957a4b35923.png)

Connecté avec un user non admin sur serveur Epsitest (Epsitest 2.8.1)
![image](https://user-images.githubusercontent.com/46866540/221368658-827ce71d-5e64-4c57-ad06-91dbfb93faf7.png)

J'a re-sync les intégrations sur le serveur de Cindor (Epsibot 2.8.1), et j'ai pas le même screen que t'avais
![image](https://user-images.githubusercontent.com/46866540/221368825-bac3c47f-85f1-410a-a918-65ab1a92f836.png)

Pourtant Epsibot a pas changé, je sais pas ce qu'il s'est passé, mais j'ai l'impression que y'a pas de bug

**Comment by Wyzedix** [comment]
@Enaxom j'te laisse rouvrir l'issue si t'arrives à reproduire
