### ISSUE TITLE
Mettre le paramètre de description de queue optionnel

### ISSUE THREAD

**Issue by Enaxom** [EpsiTeam/epsibot#132]
Quand on ajoute un élément à la queue, il faut forcément un paramètre de description qui sera caché aux utilisateurs, ce paramètre devrait être optionnel

**Comment by Wyzedix** [comment]
Moving issue to linear: [EPS-3](https://linear.app/wyzedix-lab/issue/EPS-3/parametre-hidden-information-optionnel)
