### ISSUE TITLE
Cooldown pour les commandes custom

### ISSUE THREAD

**Issue by Enaxom** [EpsiTeam/epsibot#133]
Ce serait bien d'avoir un cooldown possible pour l'exécution des commandes

**Comment by Wyzedix** [comment]
- Cooldown par commande, ou par commande par channel ?
- Il se passe quoi si on lance une commande en CD ?
  - Message d'erreur ?
  - Rien ?
- Est-ce qu'on peut avoir une commande autodelete avec un CD ? Si oui, est-ce que le message est delete si la commande était en CD ?

**Comment by Wyzedix** [comment]
Moving issue to linear: [EPS-4](https://linear.app/wyzedix-lab/issue/EPS-4/cooldown-pour-les-commandes-custom)
