### ISSUE TITLE
Logs pour l'utilisation des slahs commandes & commandes

### ISSUE THREAD

**Issue by Enaxom** [EpsiTeam/epsibot#149]
Avoir des logs pour tracer les utilisations des différentes commandes.
User a lancé un shifumi
User a appelé cette commande

**Comment by Wyzedix** [comment]
Moving issue to linear: [EPS-6](https://linear.app/wyzedix-lab/issue/EPS-6/logs-pour-lutilisation-des-slash-commandes-and-commandes-custom)
