### ISSUE TITLE
Paramètre optionnel lors de l'ajout de commande pour choisir une catégorie

### ISSUE THREAD

**Issue by Enaxom** [EpsiTeam/epsibot#150]
Lorsqu'on créé une commande, il faudrait pouvoir choisir si cette commande doit répondre uniquement dans une catégorie indiquée, afin que si un utilisateur tente de la lancer dans une autre catégorie, le bot ne réponde pas.

**Comment by Wyzedix** [comment]
Moving issue to linear: [EPS-7](https://linear.app/wyzedix-lab/issue/EPS-7/limiter-une-commande-custom-sur-une-categorie)
